#!/usr/bin/env bash
# Generate the Homebrew formula for a published kolk release.
#
#   ./scripts/update-homebrew-tap.sh v1.3.0 [> Formula/kolk.rb]
#
# Reads the release's own checksums.txt over HTTPS and emits a formula pinned to
# those digests. It never builds, never signs and never pushes: the output is the
# whole product, so a human can read it before it lands in the tap.
#
# A formula rather than a cask on purpose. GoReleaser now prefers homebrew_casks,
# but a cask is macOS-only and kolk supports Linux, where Homebrew has formulae
# and no casks. One formula covers both.
set -euo pipefail

VERSION="${1:-}"
if [ -z "$VERSION" ]; then
  echo "usage: $0 <tag>   e.g. $0 v1.3.0" >&2
  exit 2
fi
case "$VERSION" in
  v*) ;;
  *) echo "tag must start with v: $VERSION" >&2; exit 2 ;;
esac
BARE="${VERSION#v}"

REPO="onembyte/kolkrabbi"
BASE="https://github.com/$REPO/releases/download/$VERSION"
SUMS="$(curl -fsSL "$BASE/checksums.txt")" || {
  echo "no checksums.txt for $VERSION — is the release published?" >&2
  exit 1
}

digest() {
  local archive="kolk_${BARE}_$1.tar.gz" line
  line="$(printf '%s\n' "$SUMS" | grep -F " $archive" || true)"
  if [ -z "$line" ]; then
    echo "checksums.txt has no entry for $archive" >&2
    exit 1
  fi
  printf '%s' "${line%% *}"
}

DARWIN_ARM="$(digest darwin_arm64)"
DARWIN_AMD="$(digest darwin_amd64)"
LINUX_ARM="$(digest linux_arm64)"
LINUX_AMD="$(digest linux_amd64)"

for d in "$DARWIN_ARM" "$DARWIN_AMD" "$LINUX_ARM" "$LINUX_AMD"; do
  case "$d" in
    [0-9a-f]*) [ ${#d} -eq 64 ] || { echo "digest is not SHA-256: $d" >&2; exit 1; } ;;
    *) echo "digest is not hex: $d" >&2; exit 1 ;;
  esac
done

cat <<FORMULA
# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-tap.sh in onembyte/kolkrabbi.
# Do not edit by hand: regenerate it from the release's own checksums.txt.
class Kolk < Formula
  desc "Model-agnostic AI coding agent for the terminal"
  homepage "https://kolkrabbi.francomichetti.com/"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "$BASE/kolk_${BARE}_darwin_arm64.tar.gz"
      sha256 "$DARWIN_ARM"
    end
    on_intel do
      url "$BASE/kolk_${BARE}_darwin_amd64.tar.gz"
      sha256 "$DARWIN_AMD"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/kolk_${BARE}_linux_arm64.tar.gz"
      sha256 "$LINUX_ARM"
    end
    on_intel do
      url "$BASE/kolk_${BARE}_linux_amd64.tar.gz"
      sha256 "$LINUX_AMD"
    end
  end

  def install
    bin.install "kolk"
  end

  test do
    assert_match "kolk", shell_output("#{bin}/kolk help")
  end
end
FORMULA
